<?php

namespace Database\Seeders;

use App\Models\Servidor;
use Illuminate\Database\Seeder;

class ServidorSpeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $servidor1=Servidor::create(['user_id'=>'2','genero_id'=>'2','estado_civil_id'=>'1','formacion_id'=>'4','unidad_id'=>'3','tipo_contrato_id'=>'4','grupo_id'=>'6','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1001333713','nombre'=>'MINANGO NARVAEZ GLORIA MARIA','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1001333713','email'=>'1001333713@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>1000]);
        $servidor2=Servidor::create(['user_id'=>'3','genero_id'=>'2','estado_civil_id'=>'2','formacion_id'=>'3','unidad_id'=>'4','tipo_contrato_id'=>'2','grupo_id'=>'3','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1103884134','nombre'=>'GUALAN JAPON ROSA VIRGINIA','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1103884134','email'=>'1103884134@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>2000]);
        $servidor3=Servidor::create(['user_id'=>'4','genero_id'=>'2','estado_civil_id'=>'3','formacion_id'=>'2','unidad_id'=>'3','tipo_contrato_id'=>'4','grupo_id'=>'2','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1706067194','nombre'=>'CALDERON CAMPOVERDE CONSUELO DEL ROCIO','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1706067194','email'=>'1706067194@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>1200]);
        $servidor4=Servidor::create(['user_id'=>'5','genero_id'=>'2','estado_civil_id'=>'4','formacion_id'=>'4','unidad_id'=>'3','tipo_contrato_id'=>'4','grupo_id'=>'5','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1706320437','nombre'=>'TORRES DAVILA MARIA SOLEDAD','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1706320437','email'=>'1706320437@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>1200]);
        $servidor5=Servidor::create(['user_id'=>'6','genero_id'=>'2','estado_civil_id'=>'4','formacion_id'=>'3','unidad_id'=>'3','tipo_contrato_id'=>'4','grupo_id'=>'1','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1706960729','nombre'=>'CHILE RIVERA ROSA LILIANA','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1706960729','email'=>'1706960729@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>1200]);
        $servidor6=Servidor::create(['user_id'=>'7','genero_id'=>'2','estado_civil_id'=>'1','formacion_id'=>'4','unidad_id'=>'3','tipo_contrato_id'=>'4','grupo_id'=>'6','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1707218473','nombre'=>'PUENTE HERNANDEZ SOLEDAD DE LOURDES','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1707218473','email'=>'1707218473@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>1200]);
        $servidor7=Servidor::create(['user_id'=>'8','genero_id'=>'2','estado_civil_id'=>'2','formacion_id'=>'4','unidad_id'=>'3','tipo_contrato_id'=>'3','grupo_id'=>'6','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1709582637','nombre'=>'TELLO TORRES NANCI LEONOR','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1709582637','email'=>'1709582637@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor8=Servidor::create(['user_id'=>'9','genero_id'=>'2','estado_civil_id'=>'3','formacion_id'=>'4','unidad_id'=>'4','tipo_contrato_id'=>'4','grupo_id'=>'2','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1710127059','nombre'=>'PONCE GUERRERO SORAYA VALENTINA','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1710127059','email'=>'1710127059@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>4500]);
        $servidor9=Servidor::create(['user_id'=>'10','genero_id'=>'1','estado_civil_id'=>'4','formacion_id'=>'3','unidad_id'=>'6','tipo_contrato_id'=>'3','grupo_id'=>'1','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1710429257','nombre'=>'FALCON GARZON LENIN ABDON','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1710429257','email'=>'1710429257@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor10=Servidor::create(['user_id'=>'11','genero_id'=>'2','estado_civil_id'=>'4','formacion_id'=>'3','unidad_id'=>'3','tipo_contrato_id'=>'1','grupo_id'=>'6','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1710465137','nombre'=>'CYNTHIA ARACELLI FERREIRA SALAZAR','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1710465137','email'=>'1710465137@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>1200]);
        $servidor11=Servidor::create(['user_id'=>'12','genero_id'=>'2','estado_civil_id'=>'1','formacion_id'=>'4','unidad_id'=>'6','tipo_contrato_id'=>'4','grupo_id'=>'6','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1711076438','nombre'=>'BALAREZO BUSTAMANTE ROCIO DEL PILAR','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1711076438','email'=>'1711076438@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>1200]);
        $servidor12=Servidor::create(['user_id'=>'13','genero_id'=>'2','estado_civil_id'=>'2','formacion_id'=>'4','unidad_id'=>'3','tipo_contrato_id'=>'4','grupo_id'=>'5','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1711194462','nombre'=>'MUÑOZ SOTOMAYOR ELIANA MARIBEL','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1711194462','email'=>'1711194462@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>1200]);
        $servidor13=Servidor::create(['user_id'=>'14','genero_id'=>'2','estado_civil_id'=>'3','formacion_id'=>'3','unidad_id'=>'5','tipo_contrato_id'=>'1','grupo_id'=>'1','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1712032265','nombre'=>'KARINA DEL ROCÍO NÚÑEZ SALVADOR','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1712032265','email'=>'1712032265@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor14=Servidor::create(['user_id'=>'15','genero_id'=>'2','estado_civil_id'=>'4','formacion_id'=>'4','unidad_id'=>'2','tipo_contrato_id'=>'4','grupo_id'=>'5','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1712227162','nombre'=>'ZAPATA ROSERO SANDRA ELIZABETH','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1712227162','email'=>'1712227162@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor15=Servidor::create(['user_id'=>'16','genero_id'=>'2','estado_civil_id'=>'4','formacion_id'=>'3','unidad_id'=>'3','tipo_contrato_id'=>'2','grupo_id'=>'4','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1712336476','nombre'=>'VILLENA CARRERA DAPHNE ESTEFANIA','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1712336476','email'=>'1712336476@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor16=Servidor::create(['user_id'=>'17','genero_id'=>'2','estado_civil_id'=>'1','formacion_id'=>'4','unidad_id'=>'3','tipo_contrato_id'=>'4','grupo_id'=>'6','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1714042536','nombre'=>'DUQUE VANEGAS JANINA MARIA','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1714042536','email'=>'1714042536@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor17=Servidor::create(['user_id'=>'18','genero_id'=>'2','estado_civil_id'=>'2','formacion_id'=>'2','unidad_id'=>'4','tipo_contrato_id'=>'4','grupo_id'=>'1','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1714067137','nombre'=>'UNDA RODRIGUEZ GABRIELA JOHANNA','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1714067137','email'=>'1714067137@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor18=Servidor::create(['user_id'=>'19','genero_id'=>'2','estado_civil_id'=>'3','formacion_id'=>'3','unidad_id'=>'4','tipo_contrato_id'=>'2','grupo_id'=>'2','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1714628268','nombre'=>'QUIMBIURCO VALLADARES SILVIA FERNANDA','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1714628268','email'=>'1714628268@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor19=Servidor::create(['user_id'=>'20','genero_id'=>'2','estado_civil_id'=>'4','formacion_id'=>'2','unidad_id'=>'3','tipo_contrato_id'=>'3','grupo_id'=>'2','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1715613525','nombre'=>'OSORIO MENA MERICI LEONILA','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1715613525','email'=>'1715613525@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor20=Servidor::create(['user_id'=>'21','genero_id'=>'2','estado_civil_id'=>'4','formacion_id'=>'4','unidad_id'=>'4','tipo_contrato_id'=>'1','grupo_id'=>'4','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1716229255','nombre'=>'IBARRA JÁCOME MARÍA GABRIELA','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1716229255','email'=>'1716229255@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor21=Servidor::create(['user_id'=>'22','genero_id'=>'2','estado_civil_id'=>'1','formacion_id'=>'3','unidad_id'=>'4','tipo_contrato_id'=>'3','grupo_id'=>'2','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1716553241','nombre'=>'PAREDES CHAVEZ GLORIA DEL CARMEN','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1716553241','email'=>'1716553241@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor22=Servidor::create(['user_id'=>'23','genero_id'=>'2','estado_civil_id'=>'2','formacion_id'=>'2','unidad_id'=>'4','tipo_contrato_id'=>'3','grupo_id'=>'2','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1716680549','nombre'=>'MORENO VILLAFUERTE GINA PAOLA','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1716680549','email'=>'1716680549@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor23=Servidor::create(['user_id'=>'24','genero_id'=>'1','estado_civil_id'=>'3','formacion_id'=>'3','unidad_id'=>'4','tipo_contrato_id'=>'2','grupo_id'=>'2','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1719109108','nombre'=>'COLLAGUAZO ANDRANGO WILLIAN FERNANDO','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1719109108','email'=>'1719109108@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor24=Servidor::create(['user_id'=>'25','genero_id'=>'2','estado_civil_id'=>'4','formacion_id'=>'3','unidad_id'=>'4','tipo_contrato_id'=>'3','grupo_id'=>'3','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1719150078','nombre'=>'ARMIJOS ALBAN LESSLIE TALIA','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1719150078','email'=>'1719150078@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor25=Servidor::create(['user_id'=>'26','genero_id'=>'2','estado_civil_id'=>'4','formacion_id'=>'4','unidad_id'=>'3','tipo_contrato_id'=>'3','grupo_id'=>'5','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1719292078','nombre'=>'GARCIA DIAZ LIDIA RAQUEL','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1719292078','email'=>'1719292078@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor26=Servidor::create(['user_id'=>'27','genero_id'=>'1','estado_civil_id'=>'1','formacion_id'=>'4','unidad_id'=>'5','tipo_contrato_id'=>'2','grupo_id'=>'4','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1719703900','nombre'=>'ESCOBAR SALAZAR CHRISTIAN PAÚL','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1719703900','email'=>'1719703900@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor27=Servidor::create(['user_id'=>'28','genero_id'=>'2','estado_civil_id'=>'2','formacion_id'=>'4','unidad_id'=>'3','tipo_contrato_id'=>'3','grupo_id'=>'5','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1720062809','nombre'=>'FLORES GRANDA MONICA ALEXANDRA','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1720062809','email'=>'1720062809@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor28=Servidor::create(['user_id'=>'29','genero_id'=>'2','estado_civil_id'=>'3','formacion_id'=>'3','unidad_id'=>'4','tipo_contrato_id'=>'3','grupo_id'=>'6','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1721688867','nombre'=>'OLALLA ORTIZ PAULA ISABEL','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1721688867','email'=>'1721688867@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor29=Servidor::create(['user_id'=>'30','genero_id'=>'2','estado_civil_id'=>'4','formacion_id'=>'3','unidad_id'=>'4','tipo_contrato_id'=>'2','grupo_id'=>'1','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'0102107281','nombre'=>'CRESPO ORTEGA BERTHA ELIZABETH','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'0102107281','email'=>'0102107281@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor30=Servidor::create(['user_id'=>'31','genero_id'=>'2','estado_civil_id'=>'4','formacion_id'=>'4','unidad_id'=>'2','tipo_contrato_id'=>'1','grupo_id'=>'2','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'0105483150','nombre'=>'ORTIZ TORRES ESTEFANIA MARIELA','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'0105483150','email'=>'0105483150@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor31=Servidor::create(['user_id'=>'32','genero_id'=>'2','estado_civil_id'=>'1','formacion_id'=>'3','unidad_id'=>'3','tipo_contrato_id'=>'4','grupo_id'=>'3','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'0201655784','nombre'=>'GARCIA GARCIA KARINA ALEXANDRA','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'0201655784','email'=>'0201655784@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor32=Servidor::create(['user_id'=>'33','genero_id'=>'2','estado_civil_id'=>'2','formacion_id'=>'3','unidad_id'=>'4','tipo_contrato_id'=>'2','grupo_id'=>'2','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'0201985173','nombre'=>'AREVALO LEMA DIANA FERNANDA','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'0201985173','email'=>'0201985173@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor33=Servidor::create(['user_id'=>'34','genero_id'=>'2','estado_civil_id'=>'3','formacion_id'=>'3','unidad_id'=>'3','tipo_contrato_id'=>'1','grupo_id'=>'4','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'0502741978','nombre'=>'ERIKA VANESSA GALLARDO BUSTILLOS','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'0502741978','email'=>'0502741978@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor34=Servidor::create(['user_id'=>'35','genero_id'=>'2','estado_civil_id'=>'4','formacion_id'=>'4','unidad_id'=>'3','tipo_contrato_id'=>'4','grupo_id'=>'6','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'0703184143','nombre'=>'MANZO ZAMORA CECILIA AZUCENA','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'0703184143','email'=>'0703184143@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor35=Servidor::create(['user_id'=>'36','genero_id'=>'1','estado_civil_id'=>'4','formacion_id'=>'4','unidad_id'=>'3','tipo_contrato_id'=>'4','grupo_id'=>'5','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'0918233149','nombre'=>'SANCHO ORDOÑEZ FERNANDO ISAAC','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'0918233149','email'=>'0918233149@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor36=Servidor::create(['user_id'=>'37','genero_id'=>'1','estado_civil_id'=>'1','formacion_id'=>'2','unidad_id'=>'4','tipo_contrato_id'=>'1','grupo_id'=>'2','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1002711628','nombre'=>'BORJA MINDA JOSE FRANCISCO','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1002711628','email'=>'1002711628@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);
        $servidor37=Servidor::create(['user_id'=>'38','genero_id'=>'1','estado_civil_id'=>'2','formacion_id'=>'1','unidad_id'=>'4','tipo_contrato_id'=>'1','grupo_id'=>'2','etnia_id'=>'4','nacionalidad_id'=>'1','discapacidad_id'=>'1','cedula'=>'1711147262','nombre'=>'SANCHEZ MENDEZ LUIS FERNANDO','foto'=>'','fecha_nacimiento'=>'2000/01/01','telefono'=>'1711147262','email'=>'1711147262@cnig.gob.ec','email_personal'=>'','puesto'=>'puesto','partida'=>'partida','fecha_ingreso'=>'2000/01/01','lugar_nacimiento'=>'','direccion'=>'direccion','alimentacion'=>false,'transporte'=>false,'recidencia'=>false,'saldo_vacaciones'=>33]);

        
    }
}
